### ISSUE TITLE
今天的更新导致无法使用刷图规划

### ISSUE THREAD

**Issue by Ericli0708** [gneko/aktools-issues#1]
傍晚开始就无法使用刷图规划了，删除了cookie缓存还是不行。我使用的是火狐浏览器， 错误信息在附件
[Error.txt](https://github.com/graueneko/aktools/files/4470237/Error.txt)
。

**Comment by Ericli0708** [comment]
Content Security Policy: 页面设置阻止读取位于 https://planner.penguin-stats.io/plan/ 的一项资源("connect-src")。 polyfills-es2015.js:1:34909


ERROR 
{…}
​
error: error
​​
bubbles: false
​​
cancelBubble: false
​​
cancelable: false
​​
composed: false
​​
currentTarget: null
​​
defaultPrevented: false
​​
eventPhase: 0
​​
explicitOriginalTarget: XMLHttpRequest { __zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "https://planner.penguin-stats.io/plan/", __zone_symbol__xhrScheduled: true, … }
​​
isTrusted: true
​​
lengthComputable: false
​​
loaded: 0
​​
originalTarget: XMLHttpRequest { __zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "https://planner.penguin-stats.io/plan/", __zone_symbol__xhrScheduled: true, … }
​​
returnValue: true
​​
srcElement: XMLHttpRequest { __zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "https://planner.penguin-stats.io/plan/", __zone_symbol__xhrScheduled: true, … }
​​
target: XMLHttpRequest { __zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "https://planner.penguin-stats.io/plan/", __zone_symbol__xhrScheduled: true, … }
​​
timeStamp: 217086
​​
total: 0
​​
type: "error"
​​
<get isTrusted()>: function isTrusted()
​​
<prototype>: ProgressEventPrototype { lengthComputable: Getter, loaded: Getter, total: Getter, … }
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, headers: Map(0) }
​
message: "Http failure response for https://planner.penguin-stats.io/plan/: 0 Unknown Error"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 0
​
statusText: "Unknown Error"
​
url: "https://planner.penguin-stats.io/plan/"
​
<prototype>: Object { … }
main-es2015.js:1:144411
    Nn https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    handleError https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    next https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    r https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    __tryOrUnsub https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    next https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    _next https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    next https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    next https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    emit https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    onHandleError https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    invoke https://www.bigfun.cn/static/aktools/1586757532/js/polyfills-es2015.js:1
    run https://www.bigfun.cn/static/aktools/1586757532/js/polyfills-es2015.js:1
    runOutsideAngular https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    onHandleError https://www.bigfun.cn/static/aktools/1586757532/js/main-es2015.js:1
    handleError https://www.bigfun.cn/static/aktools/1586757532/js/polyfills-es2015.js:1
    runTask https://www.bigfun.cn/static/aktools/1586757532/js/polyfills-es2015.js:1
    invokeTask https://www.bigfun.cn/static/aktools/1586757532/js/polyfills-es2015.js:1
    invoke https://www.bigfun.cn/static/aktools/1586757532/js/polyfills-es2015.js:1
    0 https://www.bigfun.cn/static/aktools/1586757532/js/polyfills-es2015.js:1

**Comment by Ericli0708** [comment]
使用chrome也是一样的报错。

**Comment by gneko** [comment]
这是由于bigfun Apache/Nginx 配置策略导致，无法从纯前端的角度来解决。

bigfun是商业公司，有自己的运维考量，所以无法要求他们因为这个功能修改运维策略。

因此，这项功能会在下次更新后下线，请理解。

**Comment by Ericli0708** [comment]
LMAO，那这个所谓的“工具箱”也没啥用了，不是我理不理解的问题。

**Comment by IbarakiKasen** [comment]
> bigfun是商业公司，有自己的运维考量，所以无法要求他们因为这个功能修改运维策略。

Is this project sold to a commercial company?
