### ISSUE TITLE
11月1日更新后新加入材料缺失

### ISSUE THREAD

**Issue by odd021** [gneko/aktools-issues#8]
虽然干员数据更新了，但没有新材料的数据导致无法对新干员进行材料计算
新材料“晶体元件”（蓝），“晶体电路”（紫）, "晶体电子单元"（金）

**Comment by odd021** [comment]
另外公开招募新增黑，赫拉格，格劳克斯，星极，苏苏洛与桃金娘
希望能更新

**Comment by gneko** [comment]
已补充，应该很快就能看到了。
